name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  floor: ^1.5.0
  dio: ^5.8.0+1
  logger: ^2.5.0
  retrofit: ^4.4.2
  sqflite: ^2.4.1
  json_annotation: ^4.9.0
  retrofit_generator: ^9.1.5
  provider: ^6.1.2
  get_it: ^8.0.3
  rxdart: ^0.28.0
  web_socket_channel: ^3.0.2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  floor_generator: ^1.5.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
